config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from users.views import UserRegistrationView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='project-list'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', UserRegistrationView.as_view(), name='signup'),
    path('risk/', include('risk.urls'))
]

risk/urls.py
from django.urls import path

from .views import (IssueCreateView, IssueDeleteView, IssueDetailView, IssueUpdateView, MatrixView, ProjectCreateTask, 
                    ProjectCreateTaskInPhase, ProjectCreateView, ProjectDeleteView, ProjectLogFrameUpdate, 
                    ProjectTimeSheetView, ProjectWorkersView, ProjectRiskRegisterView,
                    ProjectDetailView, ProjectListView, ProjectPhaseCreateView, ProjectLogFrameView,
                    ProjectPhaseDeleteView, ProjectPhaseDetailView, ProjectIssuesView, ProjectTasksView,
                    ProjectPhaseUpdateView, ProjectUpdateView, RiskCreateView,
                    RiskDeleteView, RiskDetailView, RiskListView, RiskProjectCreateView,
                    RiskUpdateView, StatsView, TaskDeleteView, TaskDetailView, TaskUpdateView, generate_pdf)


urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project-list'),
    path('projects/<int:pk>/workers/', ProjectWorkersView.as_view(), name='project-workers'),
    path('project/create/', ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('project/<int:pk>/riskregister/', ProjectRiskRegisterView.as_view(), name='project-risk-register'),
    path('project/<int:pk>/risk/create/', RiskProjectCreateView.as_view(), name='project-risk-create'),
    path('project/<int:pk>/logframe/', ProjectLogFrameView.as_view(), name='project-logframe'),
    path('project/<int:pk>/logframe/update', ProjectLogFrameUpdate.as_view(), name='update-lfa'),
    path('project/<int:pk>/issues/', ProjectIssuesView.as_view(), name='project-issues'),
    path('project/<int:pk>/tasks/', ProjectTasksView.as_view(), name='project-tasks'),
    path('project/<int:pk>/timesheet/', ProjectTimeSheetView.as_view(), name='project-timesheet-view'),
    path('project/<int:pk>/task/create/', ProjectCreateTask.as_view(), name='project-task-create'),
    path('project/<int:project_id>/issues/create/', IssueCreateView.as_view(), name='project-issue-create'),
    path('project/<int:project_id>/issues/<int:pk>/update/', IssueUpdateView.as_view(), name='project-issue-update'),
    path('project/<int:project_id>/issue/<int:pk>', IssueDetailView.as_view(), name='project-issue-detail'),
    path('project/<int:project_id>/issues/<int:pk>/delete/', IssueDeleteView.as_view(), name='project-issue-delete'),
    path('project/<int:project_id>/task/<int:pk>/update/',TaskUpdateView.as_view(), name='project-task-change'),
    path('project/<int:project_id>/task/<int:pk>/delete', TaskDeleteView.as_view(), name = 'task-delete'),
    path('project/<int:project_id>/task/<int:pk>/detail',TaskDetailView.as_view(), name = 'project-task-detail'),
    path('project/<int:project_id>/phase/create/', ProjectPhaseCreateView.as_view(), name='project-phase-create'),
    path('project/<int:project_id>/phase/<int:pk>/update/', ProjectPhaseUpdateView.as_view(), name='project-phase-update'),
    path('project/<int:project_id>/phase/<int:pk>/', ProjectPhaseDetailView.as_view(), name='project-phase-detail'),
    path('project/<int:project_id>/phase/<int:pk>/delete/', ProjectPhaseDeleteView.as_view(), name='project-phase-delete'),
    path('project/<int:project_id>/phase/<int:phase_id>/task/create/',ProjectCreateTaskInPhase.as_view(), name='create-task-phase'),
    path('project/<int:project_id>/phase/<int:phase_id>/risk/create/', RiskCreateView.as_view(), name='risk-create'),
    path('project/<int:project_id>/phase/<int:phase_id>/risk/<int:pk>/update/', RiskUpdateView.as_view(), name='risk-update'),
    path('project/<int:project_id>/phase/<int:phase_id>/risk/<int:pk>/', RiskDetailView.as_view(), name='risk-detail'),
    path('project/<int:project_id>/phase/<int:phase_id>/risk/<int:pk>/delete/', RiskDeleteView.as_view(), name='risk-delete'),
    path('project/print/risk/<int:risk_id>/', generate_pdf, name='risk-print'),
    path('project/<int:project_id>/register/', RiskListView.as_view(), name='risk-register'),
    path('project/<int:project_id>/matrix/', MatrixView.as_view(), name='matrix'),
    path('stats/', StatsView.as_view(), name='stats')
]

risk/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _


class ActiveQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def inactive(self):
        return self.filter(is_active=False)

    def delete(self):
        self.update(is_active=False)


class ActiveManager(models.Manager):
    def get_queryset(self):
        return ActiveQuerySet(self.model, using=self._db)


class ActiveModel(models.Model):
    is_active = models.BooleanField(default=True, editable=False)

    objects = ActiveManager()

    class Meta:
        abstract = True

    def delete(self):
        self.is_active = False
        self.save()


class Company(models.Model):
    name = models.CharField(max_length=255)
    logo = models.BinaryField()
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

class LFA(ActiveModel):
    g1 = models.TextField('G1',  default="Goal")
    g2 = models.TextField('G2',  default="Why")
    g3 = models.TextField('G3',  default="What")
    g4 = models.TextField('G4',  default="How")

    p1 = models.TextField('P1',  default="Purpose")
    p2 = models.TextField('P2',  default="Why")
    p3 = models.TextField('P3',  default="What")
    p4 = models.TextField('P4',  default="How")

    o1 = models.TextField('O1',  default="Outcomes")
    o2 = models.TextField('O2',  default="Why")
    o3 = models.TextField('O3',  default="What")
    o4 = models.TextField('O4',  default="How")

    i1 = models.TextField('I1',  default="Inputs")
    i2 = models.TextField('I2',  default="Why")
    i3 = models.TextField('I3',  default="What")
    i4 = models.TextField('I4',  default="How")

    def __str__(self):
        return self.name

class Issue(models.Model):
    class IssueState(models.TextChoices):
        ASAP = 'ASAP', _('ASAP')
        HIGH_PRIORITY = 'HIGH-PRIORITY', _('HIGH PRIORITY')
        OPEN = 'OPEN', _('OPEN')
        DONE = 'CLOSED', _('CLOSED')

    name = models.CharField(max_length=20)
    issueID = models.DecimalField(max_digits=10, decimal_places=0)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)

    issuestate = models.CharField(max_length=20, choices=IssueState.choices, default=IssueState.OPEN)
    issue_dev = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name ='issue_dev_ASSIGNED', null=True)
    issue_check = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='issue_check_CHECKED', null=True)
    description = models.CharField(max_length=255)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['project', 'issueID'], name='unique_issue')
        ]

    def get_absolute_url(self):
        return reverse('project-issues', kwargs={'pk': self.project.pk})

    def __str__(self):
        return self.name


class Task(models.Model):
    class TaskState(models.TextChoices):
        NOT_ASSIGNED = 'NOT_ASSIGNED', _('NOT ASSIGNED')
        ASSIGNED = 'ASSIGNED', _('ASSIGNED')
        DONE_NOT_CHECKED = 'DONE_NOT_CHECKED', _('DONE NOT CHECKED')
        DONE_AND_CHECKED = 'DONE_AND_CHECKED', _('DONE AND CHECKED')

    name = models.CharField(max_length=20)
    taskID = models.DecimalField(max_digits=10, decimal_places=0)
    add_date = models.DateField(auto_now_add=True)
    final_date = models.DateField()
    real_final_date = models.DateField(null=True, blank=True)
    taskstate = models.CharField(max_length=20, choices=TaskState.choices, default=TaskState.NOT_ASSIGNED)
    task_dev = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name ='task_dev_ASSIGNED', null=True)
    task_check = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='task_check_CHECKED', null=True)
    description = models.CharField(max_length=255)
    project_phase = models.ForeignKey('ProjectPhase', on_delete=models.CASCADE, related_name="tasks")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['project_phase', 'taskID'], name='unique_task')
        ]
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tasks-detail', kwargs={'project_id': self.project_phase.project.pk, 'project_phase': self.project_phase.pk, 'pk': self.pk})
    


class Risk(models.Model):

    class State(models.TextChoices):
        ACTIVE = 'Active', _('Active')
        CLOSED = 'Closed', _('Closed')
        HAPPENED = 'Happened', _('Happened')

    class Impact(models.TextChoices):
        VVD = 'VHI', _('Very high impact')
        VD = 'HI', _('High impact')
        SD = 'MI', _('Middle impact')
        MD = 'SI', _('Small impact')
        VMD = 'VSI', _('Very small impact')

    class Probability(models.TextChoices):
        VVP = 'VHP', _('Very high probability')
        VP = 'HP', _('High probability')
        SP = 'MP', _('Middle probability')
        NP = 'SP', _('Small probability')
        VNP = 'VSP', _('Very small probability')

    risk_assignee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    project_phase = models.ForeignKey('ProjectPhase', on_delete=models.CASCADE)
    risk_type = models.ForeignKey('RiskType', on_delete=models.CASCADE, null=True, blank=True)
    impact = models.CharField(max_length=50, choices=Impact.choices, default=Impact.VMD)
    state = models.CharField(max_length=50, choices=State.choices, default=State.HAPPENED)
    probability = models.CharField(max_length=50, choices=Probability.choices, default=Probability.VNP)

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    threat = models.TextField()
    starter = models.TextField()
    reactions = models.TextField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    start_date = models.DateField()
    state_change_date = models.DateField(null=True, blank=True)
    reaction_date = models.DateField(null=True, blank=True)

    @property
    def risk(self):
        matrix = [
            ['VHRV', 'VHRV', 'HRV', 'HRV', 'MRV'],
            ['VHRV', 'VHRV', 'HRV', 'MRV', 'SRV'],
            ['HRV', 'HRV', 'MRV', 'SRV', 'SRV'],
            ['HRV', 'MRV', 'SRV', 'VSRV', 'VSRV'],
            ['MRV', 'SRV', 'SRV', 'VSRV', 'VSRV']
        ]

        proba_to_id = dict(zip(map(lambda x: x[0], self.Probability.choices), range(0, len(self.Probability))))
        impacts_to_id = dict(zip(map(lambda x: x[0], self.Impact.choices), range(0, len(self.Impact))))

        return matrix[proba_to_id[self.probability]][impacts_to_id[self.impact]]

    def get_absolute_url(self):
        return reverse('risk-detail', kwargs={'project_id': self.project_phase.project.pk, 'phase_id': self.project_phase.pk, 'pk': self.pk})


class Project(ActiveModel):
    project_manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='projects')
    company = models.ForeignKey('Company', on_delete=models.CASCADE)
    customers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    real_end = models.DateField(null=True, blank=True)
    estimated_end_date = models.DateField(null=True, blank=True)


    g1 = models.TextField('G1',  default="Goal")
    g2 = models.TextField('G2',  default="Why")
    g3 = models.TextField('G3',  default="What")
    g4 = models.TextField('G4',  default="How")

    p1 = models.TextField('P1',  default="Purpose")
    p2 = models.TextField('P2',  default="Why")
    p3 = models.TextField('P3',  default="What")
    p4 = models.TextField('P4',  default="How")

    o1 = models.TextField('O1',  default="Outcomes")
    o2 = models.TextField('O2',  default="Why")
    o3 = models.TextField('O3',  default="What")
    o4 = models.TextField('O4',  default="How")

    i1 = models.TextField('I1',  default="Inputs")
    i2 = models.TextField('I2',  default="Why")
    i3 = models.TextField('I3',  default="What")
    i4 = models.TextField('I4',  default="How")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project-detail', kwargs={'pk': self.pk})


class RiskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class RiskSubtype(models.Model):
    risk_type = models.ForeignKey('RiskType', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)


class ProjectPhase(ActiveModel):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField()
    real_end_date = models.DateField(null=True, blank=True)
    estimated_end_date = models.DateField(null=True, blank=True)

    phase_manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    project = models.ForeignKey('Project', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['project', 'name'], name='unique_projectphase')
        ]

    def get_absolute_url(self):
        return reverse('project-phase-detail', kwargs={'project_id': self.project.pk, 'pk': self.pk})

    def __str__(self):
        return self.name

risk/templates/risk/log_frame.html
{% extends 'risk/project_detail.html' %}
{% block title %}Log frame{% endblock title %}

{% block projekt-div %}
<div class="bg-light col-10 d-flex justify-content-center">
    <table class="table table-bordered mt-3" id="matrix">
        <thead class="thead-light">
            <th>Objectives</th>
            <th>Success Measures</th>
            <th>Verification</th>
            <th>Assumptions</th>
        </thead>
        <tbody>
            <tr>
                <td>
                    <label>{{ project.g1 }}</label>
                </td>
                <td>
                    <label>{{ project.g2 }}</label>
                </td>
                <td>
                    <label>{{ project.g3 }}</label>
                </td>
                <td>
                    <label>{{ project.g4 }}</label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>{{ project.p1 }}</label>
                </td>
                <td>
                    <label>{{ project.p2 }}</label>
                </td>
                <td>
                    <label>{{ project.p3 }}</label>
                </td>
                <td>
                    <label>{{ project.p4 }}</label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>{{ project.o1 }}</label>
                </td>
                <td>
                    <label>{{ project.o2 }}</label>
                </td>
                <td>
                    <label>{{ project.o3 }}</label>
                </td>
                <td>
                    <label>{{ project.o4 }}</label>
                </td>
            </tr>
            <tr>
                <td>
                    <label>{{ project.i1 }}</label>
                </td>
                <td>
                    <label>{{ project.i2 }}</label>
                </td>
                <td>
                    <label>{{ project.i3 }}</label>
                </td>
                <td>
                    <label>{{ project.i4 }}</label>
                </td>
            </tr>
        </tbody>
    </table>

</div>
<div class="offset-11 col-1">
    {% if perms.risk.change_risk %}
    <a class="btn btn-warning"  href="{% url 'update-lfa' project_id %}">
        Edit
    </a>
    {% endif %}</div>

{% endblock projekt-div %}

risk/templates/risk/matrix.html
{% extends 'risk/project_detail.html' %}
{% block title %}Matrix{% endblock title %}
{% block extra_css %}
<style>
    .success {
        background-color: rgba(40, 167, 69, 0.4);
    }
    .warning {
        background-color: rgba(255, 193, 7, 0.4);
    }
    .danger {
        background-color: rgba(220, 53, 69, 0.4);
    }
</style>
{% endblock extra_css %}
{% block projekt-div %}
<div class="bg-light col-10 d-flex justify-content-center">

    <table class="table table-bordered mt-3" id="matrix">
    <thead class="thead-light">
    <th></th>
    {% for impact in impacts %}
        <th>{{ impact }}</th>
    {% endfor %}
    </thead>
    <tbody>
    {% for label, cols in matrix.items %}
        <tr>
            <th>{{ label }}</th>
            {% for col in cols %}
                <td>
                    {% for risk in col %}
                        <a href="{% url 'risk-detail' project_id risk.project_phase.pk irsk.pk %}" class="text-dark"> {{ risk.name }} </a>
                    {% endfor %}
                </td>
            {% endfor %}
    {% endfor %}
    </table>
    </div>
{% endblock projekt-div %}
{% block js %}
{{ block.super }}
<script>
    let table = document.getElementById('matrix');

    table.rows[5].cells[1].classList.add('warning');
    table.rows[5].cells[2].classList.add('success');
    table.rows[5].cells[3].classList.add('success');
    table.rows[5].cells[4].classList.add('success');
    table.rows[5].cells[5].classList.add('success');

    table.rows[4].cells[1].classList.add('warning');
    table.rows[4].cells[2].classList.add('warning');
    table.rows[4].cells[3].classList.add('success');
    table.rows[4].cells[4].classList.add('success');
    table.rows[4].cells[5].classList.add('success');

    table.rows[3].cells[1].classList.add('warning');
    table.rows[3].cells[2].classList.add('warning');
    table.rows[3].cells[3].classList.add('warning');
    table.rows[3].cells[4].classList.add('success');
    table.rows[3].cells[5].classList.add('success');

    table.rows[2].cells[1].classList.add('danger');
    table.rows[2].cells[2].classList.add('danger');
    table.rows[2].cells[3].classList.add('warning');
    table.rows[2].cells[4].classList.add('warning');
    table.rows[2].cells[5].classList.add('success');

    table.rows[1].cells[1].classList.add('danger');
    table.rows[1].cells[2].classList.add('danger');
    table.rows[1].cells[3].classList.add('warning');
    table.rows[1].cells[4].classList.add('warning');
    table.rows[1].cells[5].classList.add('warning');
</script>
{% endblock js %}

risk/templates/risk/project_phase_detail.html
{% extends 'risk/project_detail.html' %}
{% block title %}Phase Detail{% endblock title %}
{% block projekt-div %}
    <div class="bg-light col-10">
        <div class="card mt-3">
            <div class="card-header">
                <h5 class="card-title">Phase detail</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <dl class="col-sm-6 row">
                        <dt class="col-sm-4">Phase name</dt>
                        <dd class="col-sm-8"> {{ object.name }}</dd>
                        <dt class="col-sm-4">State</dt>
                        <dd class="col-sm-8"> {{object.is_active|yesno:"active,inactive" }}</dd>
                        <dt class="col-sm-4">Start date</dt>
                        <dd class="col-sm-8"> {{object.start_date}} </dd>
                        <dt class="col-sm-4">Description</dt>
                        <dd class="col-sm-8"> {{object.description}}</dd>
                    </dl>
                    <dl class="col-sm-6 row">
                        <dt class="col-sm-4">Phase manager</dt>
                        <dd class="col-sm-8"> {{object.phase_manager}}</dd>
                        <dt class="col-sm-4">End date</dt>
                        <dd class="col-sm-8"> {{object.estimated_end_date|default_if_none:"-" }}</dd>

                    </dl>

                </div>
                <div class="float-right d-inline">
                    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
                        <div class="modal-dialog modal-xl" role="document">
                          <div class="modal-content"></div>
                        </div>
                    </div>
                    {% if perms.risk.change_projectphase and object.is_active %}
                        <button type="button"  id="update-phase" class=" btn btn-warning">Edit</button>
                    {% endif %}
                    {% if perms.risk.delete_projectphase and object.is_active %}
                        <button type="button" id="delete-phase" class=" btn btn-danger">Deactivate</button>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <div class="row">
                    <h5 class="card-title col-3">Tasks</h5>
    
                    <div class="col-9 ">
                        <div class="modal fade" tabindex="-1" role="dialog" id="modal">
                            <div class="modal-dialog" role="document">
                              <div class="modal-content"></div>
                            </div>
                        </div>
                        <div class="form-inline float-right">
                            <div class="dropdown mr-2">
                                <div class="form-inline">
                                    <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownPhases" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    State
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownPhases">
                                    {% for taskstate,text in taskstates %}
                                        <a class="dropdown-item" type="button" href="?taskstate={{taskstate}}">{{text}}</a>
                                    {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% if perms.risk.add_risk and object.is_active %}
                                <button id="create-task" class="btn btn-success" type="button" name="button">Add Task</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-responsive">
                <thead class="thead-light">
                    <th scope="col">Task ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Developer</th>
                    <th scope="col">Check from</th>
                    <th scope="col">State</th>
                    <th scope="col">Added</th>
                    <th scope="col">Deadline</th>
                    <th scope="col">Project phase</th>
                    <th scope="col"> </th>
                </thead>
                <tbody>
                    {% for task in tasks %}
                        <tr data-href="{% url 'project-task-change' project_id task.pk%}">
                        <td >{{task.taskID}}</td>
                        <td >{{task.name}}</td>
                        <td >{{task.task_dev}}</td>
                        <td >{{task.task_check }}</td>
                        <td >{{task.taskstate}}</td>
                        <td >{{task.add_date}}</td>
                        <td >{{task.final_date}}</td>
                        <td >{{task.project_phase}}</td>
                        <td>

                        {% if perms.risk.view_project %}
                            <button type="button" class="detail-task btn btn-sm btn-primary" data-form-url="{% url 'project-task-detail' project_id task.pk %}">
                                <span class="fa fa-pencil">Info</span>
                            </button>
                        {% endif %}        
                        </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="card mt-3">
            <div class="card-header">
                <div class="row">
                    <h5 class="card-title col-3">Risks</h5>
                    <div class="col-9 ">
                        <div class="form-inline float-right ">
                            <div class="dropdown mr-2">
                                <div class="form-inline">
                                    <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownPhases" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                                      State
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownPhases">
                                        {% for state,text in states %}
                                             <a class="dropdown-item" type="button" href="?state={{state}}">{{text}}</a>
                                        {% endfor %}
                                    </div>
                                  </div>
                            </div>
                            {% if perms.risk.add_risk and object.is_active %}
                                <button id="create-risk" class="btn btn-success" type="button" name="button">Create Risk</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-responsive">
                    <tr>
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Risk name</th>
                                <!--<th scope="col">Category</th>-->
                                <th scope="col">Threat</th>
                                <th scope="col">Starter</th>
                                <th scope="col">Owner</th>
                                <th scope="col">Risk</th>
                                <th scope="col">State</th>
                                <th scope="col">Change date</th>
                                <th scope="col"> </th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for risk in risks %}
                            <tr data-href="{% url 'risk-detail' project_id object.pk risk.pk %}">
                                <td >{{risk.name}}</td>
                                <!--<td >{{risk.risk_type}}</td>-->
                                <td >{{risk.threat}}</td>
                                <td >{{risk.starter}}</td>
                                <td >{{risk.risk_assignee}}</td>
                                <td >{{risk.risk}}</td>
                                <td >{{risk.state}}</td>
                                <td >{{risk.state_change_date|default_if_none:"-"}}</td>
                                <td>
                                    <div class="d-flex">
                                        {% if perms.risk.view_project%}
                                        <button type="button" class="detail-risk btn btn-sm btn-primary mr-2" data-form-url="{% url 'risk-detail' project_id object.pk risk.pk %}">
                                            <span class="fa fa-pencil">Detail</span>
                                        </button>
                                        {% endif %}
                                        {% comment %} {% if perms.risk.change_risk %}
                                        <button type="button" class="update-risk btn btn-sm btn-warning mr-2" data-form-url="{% url 'risk-update-phase' project_id object.pk risk.pk %}">
                                            <span class="fa fa-pencil">Edit</span>
                                        </button>
                                        {% endif %}
                                        {% if perms.risk.delete_risk %}
                                        <button type="button" class="delete-risk btn btn-sm btn-danger" data-form-url="{% url 'risk-delete' project_id object.pk risk.pk %}">
                                            <span class="fa fa-pencil">Delete</span>
                                        </button>
                                        {% endif %} {% endcomment %}
                                    </div>
                                </td>
                            </tr>
                       {% endfor %}
                        </tbody>
                </table>
            </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block js %}
{{block.super}}
<script type="text/javascript">
    $(document).ready(function() {

        $("#update-phase").modalForm({
            formURL: "{% url 'project-phase-update' project_id object.pk %}"
        });

        $("#delete-phase").modalForm({
            formURL: "{% url 'project-phase-delete' project_id object.pk  %}"
        });
        
        $("#create-task").modalForm({
            formURL: "{% url 'create-task-phase' project_id object.pk %}"
        });

        $(".detail-task").each(function () {
            $(this).modalForm({
            formURL: $(this).data("form-url"),
            });
        });

        $(".update-task").each(function () {
            $(this).modalForm({
            formURL: $(this).data("form-url"),
            });
        });

        $(".delete-task").each(function () {
            $(this).modalForm({
              formURL: $(this).data("form-url"),
            });
          });


        $(".detail-risk").each(function () {
            $(this).modalForm({
            formURL: $(this).data("form-url"),
            });
        });

        $("#create-risk").modalForm({
            formURL: "{% url 'risk-create' project_id object.pk %}"
        });

        $(".update-risk").each(function () {
          $(this).modalForm({
            formURL: $(this).data("form-url"),
          });
        });

        $(".delete-risk").each(function () {
          $(this).modalForm({
            formURL: $(this).data("form-url"),
          });
        });

        $(".table td.clickable-row").each(function() {
            $(this).css("cursor","pointer").click(function() {
              document.location = $(this).parent().data("href");
            })
        });

    });

    </script>

{% endblock js %}